local _M = {}

_M.KEY_CHANNEL_ID_INDEX = 'CHANNEL_ID_INDEX'
_M.KEY_LOGIN_CHANNEL_TOKEN = 'LOGIN_CHANNEL_TOKEN'
_M.KEY_LOGIN_USER_TOKEN = 'LOGIN_CHANNEL_TOKEN'
_M.KEY_TOKEN_TEMP = 'TOKEN_TEMP'

return _M