if not ZS_USER_STATE then ZS_USER_STATE = {} end
ZS_USER_STATE.NORMAL = 'normal'
ZS_USER_STATE.ABNORMAL = 'abnormal'


if not ZS_ACCOUNT_TYPE then ZS_ACCOUNT_TYPE = {} end
ZS_ACCOUNT_TYPE.DEFAULT = 'USER'

if not ZS_LANGUAGE_CODE then ZS_LANGUAGE_CODE = {} end
ZS_LANGUAGE_CODE.DEFAULT = SYSTEM_CONF.language_code.zh_CN.Code

if not ZS_CURRENCY_TYPE then ZS_CURRENCY_TYPE = {} end
ZS_CURRENCY_TYPE.DEFAULT = SYSTEM_CONF.coin_code.China